#this is server name
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

##Druid##
spring:
  aop:
    auto: true
#    proxy-target-class: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
    secondary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
      url: jdbc:mysql://127.0.0.1:3306/tactics?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
    tomcat:
      initial-size: 5
      min-idle: 10
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #JPA Configuration:=MYSQL
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  #Redis Properties
  redis:
    host: 192.168.23.100
    port: 6379
    password:
    timeout: 0
    expireTime: 60000
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 10
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中的最小空闲连接
      min-idle: 0


#this is logger properties
logging:
  level:
    root: ERROR

# Custom attribute values
constant:
  user:
    password: 123456
  file:
    src: D:\work\git\kexin_tactics\spring-boot-web\data
    pumpNum: 5
    splitCharacter: ","
  isDev: false
